### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by chris-martin** [chessai/qsem#1]
The `QSem` module seems like something I would like to use. I see that this package hasn't been updated in some time. Is that just because you no longer need this, or because there is something else that you might recommend instead? Do you think this package is worth revitalizing if somebody wanted to take it over?

**Comment by chessai** [comment]
I just haven't needed it in a while. It should still compile with a bumped base upper bound.

**Comment by chris-martin** [comment]
Thanks for the merge of #2. I suppose a metadata revision is in order too.

**Comment by chessai** [comment]
https://hackage.haskell.org/package/qsem-0.1.0.0/revisions/
